### ISSUE TITLE
Port as PCL?

### ISSUE THREAD

**Issue by negue** [scottrippey/SmartFormat.NET#40]
Hi,

I would like to use this Library in my Windows Store / Phone App but it is currently build for the "old" .Net 3.5 and is not PCL ready.

Anyway, I could port it, but would you merge it, once I'm done with the port, so that It'll be available via NuGet?

**Comment by SeriousM** [comment]
hi!

Is .net 4.0 enough?

**Comment by negue** [comment]
Unfortunately Windows Store / Phone Universal Apps have only a subset of the actual  .Net 4.0 (but also alot of async stuff)

I could try a PCL Version which would Target .Net 4.0 / Windows 8 / Windows Phone 8 / (maybe also silverlight) and Xamarin.Android / iOS

**Comment by scottrippey** [comment]
That's a great idea ... I would definitely want this to be available on all .NET platforms.  What changes do you anticipate for making this PCL compatible?

**Comment by negue** [comment]
Mostly it is just changed the Project's Type to a PCL one and using the Portable.targets.

but if you use some functions which are not available in the PCL Namespaces then I'd look for a workaround (haven't looked much at SmartFormat-Code yet)

Anyway here is my first ported library to a PCL: https://github.com/marska/habitrpg-api-dotnet-client/pull/10/files#diff-d9ace12a3e99ab1a5fff6a6a11705111R16

I could 
a) change the project to PCL but then all .Net3.5 Builds wouldn't work anymore
b) add a separate PCL project which just includes all Sources , then you could still provide the .Net3.5 Builds

**Comment by SeriousM** [comment]
the reason why I'm asking is that I would like to target the lowest
framework possible to avoid breaking changes for the users.

**Comment by scottrippey** [comment]
Sorry, I've got a lot of thoughts here:

1. We should do whatever is needed to make this library available to platforms (ie. yes we should add a PCL project)
2. Right now, this library is just .NET3.5, right?  Can it be used with .NET4+ as-is?  Or do we not yet support .NET4+?
3. With about 4000 Nuget downloads, it seems like we ought to maintain .NET3.5 support.  What ways can we do this?  2 project files?  It seems like that's the "standard" way to do this in .NET -- maintain multiple parallel projects within a solution.
4. I know Nuget supports multiple platform support, so that the single package can be used for all platforms.  We should ensure we do this.
5. The original library was for .NET2.0.  Is there any need to support this platform, or is it dead?  Would this require another csproj?

@SeriousM @pathoschild Can you guys answer these questions?  They've been bothering me for a while.

**Comment by SeriousM** [comment]
1. yes, that would boost the compatibility and acceptance of the library
2. .net references are backward-compatible. a 4.5 project can use any 2.0 or even 1.1 project as reference.
3. we can either add a build-script to modify the .proj file and build it in different versions, or we add separate .proj files in different versions and link the files (but that would mean to maintain all the stuff.)
4. yes, see p.3
5. why dead? see p.2

**Comment by scottrippey** [comment]
Awesome, thanks for the answers.
2. Does that mean it's a good idea to just target the 2.0 platform, since it would be forwards compatible?  I would be afraid that it would give people the impression that the library is outdated.  
3. I'm trying to research msbuild to figure out how to set it up to build each platform.

**Comment by SeriousM** [comment]
> I would be afraid that it would give people the impression that the library is outdated.

ha, that could be the impression if the package is not updated recently.
nah, tbh, people doesn't look at the version as long it is compatible.

**Comment by scottrippey** [comment]
Ok, well, by the looks of it, I think we need to add a PCL project.  

The PCL will target .NET4.0+ as well as Silverlight, Win8, WinPhone, etc.  

And we'll continue to build for .NET 3.5, too, using a separate project file.  This means we'll just need to maintain both project files, whenever a file is added or removed.

I don't think we need to support .NET 2.0, because that will require yet another project file to maintain.

**Comment by SeriousM** [comment]
> This means we'll just need to maintain both project files, whenever a file is added or removed.

is the difference in the project files that big? otherwise I would just modify the single project file during building/publishing step. you know what I mean?
