### ISSUE TITLE
Using with HTML

### ISSUE THREAD

**Issue by j055** [scottrippey/SmartFormat.NET#44]
Hi

I'm allowing users to edit format strings in an HTML editor. This works well until they use characters that require encoding, e.g.

{Contacts.Count::&amp;gt;0?&lt;ul&gt;{Contacts:&lt;li&gt;{FirstName} {LastName}&lt;/li&gt;|}&lt;/ul&gt;|}

Can you suggest a way I can decode the HTML which needs formatting without effecting encoded HTML outside the format regions? I can access the text nodes using HtmlAgilityPack.

SmartFormat.NET is an outstanding piece of work by the way.

Thank you
Andrew

**Comment by scottrippey** [comment]
Hmmm, I don't fully understand the situation ... if you're generating the HTML from a string, you shouldn't need to escape the &gt;. .But I think I can answer anyway.  
Hopefully, you can update to the recently released v1.5.  
In v1.5, the "conditional formatter" is obsolete, and is being replaced with the "choose formatter".  The choose formatter has a much better syntax than the conditional.  Here's an example:
```
{Contacts.Count:choose(0):| <ul>{Contacts:<li>{FirstName} {LastName}</li>|}</ul>}
```
I'm in the process of updating the documentation still, so I'll explain how it works with an example: `{Count:choose(1,2,3):one|two|three[|default]}`
Your input must match one of the choices, which will choose the corresponding output, or default if none match.
So, you can do `{Count:choose(0): empty | not empty}`.

**Comment by scottrippey** [comment]
I am also working on enhancing `:choose:`, so that it can support the following scenarios (but these are not yet available):
`:choose(null):` matches `null` obviously
`:choose(empty):` where `empty` will match null, empty strings, or empty collections.
`:choose(>5,<=5):` this would replace the conditional formatter's functionality
`:choose(custom):` this would allow you to register your own custom rules, in the scenario where you've got some complicated logic that you don't want to put in your template

**Comment by scottrippey** [comment]
I'm going to close this, based on the above solution

**Comment by j055** [comment]
Hi Scott

Your "choose formatter" example is an elegant solution to my problem.

Thank you

**Comment by scottrippey** [comment]
A lot of thought and work went into the `choose` syntax, and the improvements are substantial, making it a much more elegant solution than the former `conditional` syntax.  
Glad to hear it'll work for you.
