### ISSUE TITLE
colon character prevents output

### ISSUE THREAD

**Issue by chandmk** [scottrippey/SmartFormat.NET#47]
`Smart.Format("{N:Weight: {} lbs.|}", new { N = "20" })`

Expected:  `"Weight: 20 lbs."`
Result: `(empty string)`

Removing colon character works
`Smart.Format("{N:Weight {} lbs.|}", new { N = "20" })`
outputs  `"Weight 20 lbs."`

Version: 1.6.1

**Comment by scottrippey** [comment]
This is because of the "named formatter" syntax, which thinks you're trying to use a formatter called "Weight".
You should escape the 2nd colon, like `@"{N:Weight\: {} lbs.|}

**Comment by chandmk** [comment]
I didn't understand the escape sequence usage.  

Moreover this takes away the simplicity of the previous versions.  How about after piping through all  formats from all the extensions and falling back to treating "Weight" as a literal text?

**Comment by scottrippey** [comment]
Sorry, I fixed the escape code, it should've been  `@"{N:Weight\: {} lbs.|}"`.

**Comment by scottrippey** [comment]
Regarding alternative options, other than escaping it...
Currently, parsing happens before formatting, so it's not too easy to "fall back".  And currently, if the formatter isn't found, it's a formatting error.  (In Release mode, the ErrorAction is set to Ignore, so that's why you get an empty output.  If you set ErrorAction to Throw, you'd see the error).
I like the fact that an "unrecognized" formatter will throw an error instead of just output the text.  So I think I like the escape sequence.
However, I'm thinking about an alternative way to escape.  What if we did double-colon at the beginning, which would essentially say "don't use a named formatter", so that way you'd be free to use colons in your output.  Here's an example:
`"{N::Weight: {} lbs.|}"` The double-colon would avoid the ambiguity.  You could also do something like `"{N::plural(s): {}|}"`because normally, this would get parsed as `Selector: "N", FormatterName: "plural", FormatterOptions: "s", format: " {}|"`

**Comment by chandmk** [comment]
@"{N:Weight\: {} lbs.|}". This escape sequence is not working.

{N::Weight: {} lbs.|} Double colon works.  

That makes me think why not use double colon as the default for named formats?  Because while learning the named formats user already need to know what the formats are and learning about extra colon is not a complicated thing.

**Comment by scottrippey** [comment]
Hmm, interesting. Maybe better than double colon would be a different char. I'll put some thought into it.

**Comment by scottrippey** [comment]
Ok, I have an idea.  With `String.Format`, there's a feature called "alignment" with the following syntax:
`{0,-16:N2}`
So I'm thinking, perhaps named formatters could use this same syntax - using a comma instead of the colon or double-colon:
`{Value,choose(1|2|3):one|two|three}`

**Comment by gab1990** [comment]
Hello, any fix or workaround for this problem ? I'm using SmartFormat with a HTML template, so I can't escape the colon... If I use double colon, it works but I have a colon at the beginning of the output  that I don't need. Example :

With :
    {MyListOf2Values:: Value: {MyValue} |}

I get :

": Value: 12 : Value: 12 "


Thanks.

**Comment by scottrippey** [comment]
As a workaround, you could probably intentionally use the named formatter:

    {MyListOf2Values:list: Value: {MyValue} |}

I'm still considering what the long-term fix will be, because the current syntax is certainly causing some conflicts.  But for now, hopefully that works.

**Comment by scottrippey** [comment]
Should be solved with #65

**Comment by axunonb** [comment]
Will be solved in upcoming version 1.7.x shortly:
When the parser comes across a formatter name, this does not exist in the registered extensions, it will treat this part as a format, which will be processed by DefaultFormatter.

**Comment by axunonb** [comment]
Updated version committed, where test with the issues mentioned have passed: https://github.com/scottrippey/SmartFormat.NET/commit/46bbae26b6c34582887b60fc0488cd134514fde7
