### ISSUE TITLE
custom named formatter syntax

### ISSUE THREAD

**Issue by chandmk** [scottrippey/SmartFormat.NET#48]
I have a custom named formatter called `strbool`.  Which prints Yes if value is true and prints No if value is false.

In the previous version, this works fine.

`Smart.Format("{value:strbool}", new { value = true });`

Now it needs a parenthesis.  

`Smart.Format("{value:strbool()}", new { value = true });`

What it means adding a parenthesis here?  Again previous syntax felt more natural.

**Comment by scottrippey** [comment]
Currently, the Parser is responsible for determining the "named formatter".  So, this doesn't allow for flexibility.  It needs to parse `{0:yyyy}` the same way as it parses `{0:strbool}`.  
So, if there are 2 colons, or parenthesis, then it's a named formatter.  Otherwise, there is no named formatter.

**Comment by scottrippey** [comment]
To improve this, do you have any suggestions?
1) Perhaps the named formatter can be handled during "format time", where it searches for the name, and if not found, it treats it as a format string.  This would alleviate the issue in #47 as well.
2) If the named formatter used a different syntax instead of the colon (as suggested in #47), then there would be no ambiguity.

**Comment by chandmk** [comment]
I like the option 1.

**Comment by scottrippey** [comment]
Should be solved with #65

**Comment by axunonb** [comment]
Will be closed in upcoming version 1.7.x shortly:
When the parser comes across a formatter name, this does not exist in the registered extensions, it will treat this part as a format, which will be processed by DefaultFormatter.

**Comment by axunonb** [comment]
Updated version committed, where test with the issues mentioned have passed: https://github.com/scottrippey/SmartFormat.NET/commit/46bbae26b6c34582887b60fc0488cd134514fde7
