### ISSUE TITLE
Add support for DNX/.NET Core

### ISSUE THREAD

**Issue by glen-84** [scottrippey/SmartFormat.NET#59]

**Comment by SeriousM** [comment]
you're invited to [contribute](https://github.com/scottrippey/SmartFormat.NET/blob/master/CONTRIBUTING.md#pull-requests).

btw, a one-liner, even it's a good idea, is kind of unpleasant. we're providing this great piece of software for free; treat it with love.

**Comment by glen-84** [comment]
I apologize, I didn't think that a description was necessary. I will check what needs to be done in order to support DNX and .NET core.

**Comment by SeriousM** [comment]
That would be great, thank you!
Am 08.06.2015 17:13 schrieb "Glen" <notifications@github.com>:

**Comment by glen-84** [comment]
I really don't know how to retrofit this and maintain the existing project and solution files.

The best I could do is to implement this on another branch, without all the old project/solution files, etc.

**Comment by SeriousM** [comment]
I don't know what's the benefit of supporting DNX and what do you mean with .NET Core.
Could you just introduce us to the wished changes so that we can understand it without starting with the research from scratch?
Thanks

**Comment by glen-84** [comment]
[.NET Core](http://docs.asp.net/en/latest/conceptual-overview/dotnetcore.html) & [DNX](http://docs.asp.net/en/latest/dnx/overview.html).

I'm going to try to implement this on a clean branch.

**Comment by glen-84** [comment]
https://github.com/glen-84/SmartFormat.NET/tree/DNX

It's building for dnx451 (regular framework under DNX), but there are 13 errors for DNX Core (~7 unique). You'll need to go through the list and find out if there are plans to add support for certain types/methods in [.NET Core](https://github.com/dotnet/corefx/), and if not, find alternatives (assuming that you *do* want to support .NET Core).

Removed:

1. "releases" -- this is not something that's usually stored inside a source repo.
2. SmartFormat.Demo -- not sure if it's possible to run a WinForms app with DNX.
3. Extra solution files, NuGet stuff, etc. -- some things can be added back if necessary.

Notes:

1. NUnit does not yet support .NET Core ([issue](https://github.com/nunit/nunit/issues/575)). You can either wait or switch to something like xUnit.

**Comment by SeriousM** [comment]
@glen-84, when do you expect that this is supported by SmartFormat.NET? Is it something you really wait for it or do you just want to support the project?

> NUnit does not yet support .NET Core (issue). You can either wait or switch to something like xUnit.

I guess we will wait :)

**Comment by glen-84** [comment]
I was writing an implementation of an `IStringLocalizer` for ASP.NET 5 that allows the developer to use a custom string provider and string formatter, and I was going to use SmartFormat.NET and MessageFormat.NET as examples for the formatter.

i.e. It's not super-high priority.

**Comment by kaib84** [comment]
Any updates on this? Microsoft just released the next version of Visual Studio with .NET CORE and we would like to migrate our software to the new .NET version.

**Comment by axunonb** [comment]
Hi Scott,

Coming back to feature request by @glen-84:
Because I'm using SmartFormat.Net in [MailMergeLib](https://github.com/axuno/MailMergeLib), which I would like to port to .Net Core I gave this issue a try. The good news: it works with only 1 problem left:

I'm struggling with CallContext.LogicalGetData(key) and CallContext.LogicalSetData(key, value) in ListFormatter.cs. CallContext is not, and will not be ported to .Net Core by Microsoft.
Frankly I've never used these classes and I can't really figure out why they are used here.

I've compiled a VS2015 project "SmartFormat VS2015 NetCore.sln" for the .Net Core port which is attached to this post. It also provides a small console example as a proof of concept (folder "SmartFormat.NetCore.Demo").

Actually there were very few changes necessary which you can easily identify (date of files is 16 Oct 2016), and which are self-explaining or commented.

Would be great if you could help me out, or if you would even consider taking over the port into your repo.

[SmartFormatNet-NetCore.zip](https://github.com/scottrippey/SmartFormat.NET/files/531982/SmartFormatNet-NetCore.zip)

**Comment by axunonb** [comment]
Created a [Pull Request](https://github.com/scottrippey/SmartFormat.NET/pull/82) for supporting .NET Core (Standard 1.6). Any comments or discussion welcome.

**Comment by axunonb** [comment]
@scottrippey, @SeriousM: Priorities and interest in projects change, that's absolutely fine for me. Since [MailMergeLib](https://github.com/axuno/MailMergeLib) relies on SmartFormat.Net I would just like to know, whether there will be further development of this GitHub repository, or whether I'm on my own.

**Comment by scottrippey** [comment]
@axunonb Norbert, sorry for the delayed responses.  As you've correctly guessed, I'm unable to continue development of this repo, as I've been out of .NET development for many years.
I'd be happy to add you as a collaborator, if you're interested.  I'm not sure how NuGet publishing works, but I'd be willing to share my keys or transfer ownership, whatever's necessary!
Sorry about the lack of activity, I'm glad you found this package useful!

**Comment by axunonb** [comment]
@scottrippey Scott, I'm sorry to hear that, and I also think it would be a pity to stop working on SmartFormat.Net. So yes, you may add me as a collaborator and I'll try my best. With NuGet publishing I'll have to find out what to do. I'll let you know. For now thanks again for the good work with this repo.

**Comment by axunonb** [comment]
@scottrippey Scott, I had just been checking various options on how to go on with SmartFormat.Net. So:
* GitHub: A [repository transfer](https://help.github.com/articles/about-repository-transfers/) to GitHub account [axuno](https://github.com/axuno) could be the most simple thing. But this is depending on your preferences.
* NuGet: Here I understand you could add Nuget account [axuno](https://www.nuget.org/profiles/axuno) as a package owner [as described here](https://docs.nuget.org/ndocs/create-packages/publish-a-package#managing-package-owners-on-nuget-org).

**Comment by SeriousM** [comment]
Adding you as a contributor is the most simple thing because the URL stays
the same.

**Comment by scottrippey** [comment]
@axunonb I've added you as both a GitHub contributor and a Nuget Owner!  With great power comes great responsibility! :) 
Thanks in advance for your help!

**Comment by axunonb** [comment]
Okay I confirmed both, thanks. @SeriousM are you still actively contributing? I'd be interested in your opinion about this [Pull Request](https://github.com/scottrippey/SmartFormat.NET/pull/82).
I also confirmed [these issues](https://github.com/scottrippey/SmartFormat.NET/issues/75) which should be nice to "disappear".

**Comment by axunonb** [comment]
Pull request merged.

**Comment by SeriousM** [comment]
Hi Norbert, I'm not an active contributor anymore.
Sorry Scott, but my life is pretty demanding.
Cheers!

Am 01.11.2016 10:17 schrieb "Norbert Bietsch" <notifications@github.com>:
