### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by kaib84** [scottrippey/SmartFormat.NET#64]
I found the following bug, which puts invalid "}" at the end:

	class Program
	{
		public enum Gender
		{
			Unspecified = 0,
			Male = 1,
			Female = 2
		}

		static void Main(string[] args)
		{
			var result = "";
			var template = "{gender:choose(Male|Female):{last_name:choose(null):Hi,|Dear Mr {last_name},}|{last_name:choose(null):Hi,|Dear Ms {last_name},}}";

			var model1 = new
			{
				first_name = "Jane",
				last_name = "Doe",
				gender = Gender.Male
			};
			result = Smart.Format(template, model1);
			Console.WriteLine(result);

			var model2 = new
			{
				first_name = "Jane",
				last_name = "Doe",
				gender = Gender.Female
			};
			result = Smart.Format(template, model2);
			Console.WriteLine(result);

			Console.ReadLine();
		}
	}

**Comment by scottrippey** [comment]
What's happening here is that `}}` is treated as the default escape sequence for a literal `"}"`. And the parser is being forgiving, since it then thinks you're missing a closing brace.

The easiest workaround is to insert a space between them, like `} }`.  

An alternative approach is to configure an alternative escape sequence, by calling

    Smart.Default.Parser.UseAlternativeEscapeChar('\');
