### ISSUE TITLE
Change the Named Formatter syntax to use the alignment syntax

### ISSUE THREAD

**Issue by scottrippey** [scottrippey/SmartFormat.NET#65]
In v1.5, the "named formatter" feature was introduced.  However, the double-colon syntax was not fully backwards compatible, and introduced too many breaking changes.
The proposed solution is to use a similar syntax to the "alignment" syntax.  Instead of double-colon, we'd use comma-colon:
    {selector,formatter:format}
Examples:
    {Name,choose(null):Hi,|Hi {Name} }
    {Date,default:hh:mm:ss}
    {Dates,list:hh:mm:ss|, }
This should certainly be fully compatible with `String.Format`, and since the alignment feature can only be used with the `default` formatter, it seems like a good fit.
This will solve many of the "named formatter" bugs.

**Comment by axunonb** [comment]
All these issues will be solved in upcoming version 1.7.x shortly:
When the parser comes across a formatter name, this does not exist in the registered extensions, it will treat this part as a format, which will be processed by DefaultFormatter.
Generally IMHO the parser should "know" about the tokens it's expected to resolve. The "named formatters" and the regular string.Format cross their ways. That's why identifying a named formatter must not be based on "encapsulated between dots", but the string between dots must also be an existing formatter name.

**Comment by axunonb** [comment]
Updated version committed, where test with the issues mentioned have passed: https://github.com/scottrippey/SmartFormat.NET/commit/46bbae26b6c34582887b60fc0488cd134514fde7
