### ISSUE TITLE
Iterators, arrays and enumerables

### ISSUE THREAD

**Issue by mcanti** [scottrippey/SmartFormat.NET#75]
Hello,

I tried different scenarios here: https://dotnetfiddle.net/l4Mouv
Several cases don't work as expected. 
Probably it is because the ListFormatter converts the received object to ICollection, which doesn't work for this type: System.Linq.Enumerable+WhereArrayIterator`1 

Would you please look over the Fiddle and let me know what I'm doing wrong?

**Comment by axunonb** [comment]
It took a while for the answer but still it might be useful for other readers as well:

The problem starts with the fact, that SmartFormat by default suppresses any exceptions in release configuration. So with your example first let's switch exceptions on:
```csharp
Smart.Default.ErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;
Smart.Default.Parser.ErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;
```
Next, the sample code uses consecutive curly braces, which should NOT be interpreted as literals. That is why alternative escaping must be switched on:
```csharp
Smart.Default.Parser.UseAlternativeEscapeChar('\\');
```
With this in place, dotnetfiddle will throw a security exception, because SmartFormat is using System.Runtime.Remoting.Messaging.CallContext.LogicalGet|SetData which obviously is disallowed with dotnetfiddle.

Last not least the example ```Console.Out.WriteSmart("{0:{Persons.First}}", model);``` is using the extension method First(). Extension method First() is not part of a the Persons instance, but a part of System.Linq.Enumerable. Extension methods thus can never be invoked by SmartFormat.

The complete, working sample code for SmartFormat 1.7.x is:
```csharp
[Test]
public void List_Example()
{
	var data = new[]
	{
		new 	{ Name = "Person A", Gender = "M" },
		new 	{ Name = "Person B", Gender = "F"  },
		new 	{ Name = "Person C", Gender = "M" 	}
	};

	var model = new { Persons = data.Where(p => p.Gender == "M") };

	Smart.Default.Parser.UseAlternativeEscapeChar('\\');
	Smart.Default.ErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;
	Smart.Default.Parser.ErrorAction = SmartFormat.Core.Settings.ErrorAction.ThrowError;

	var result = Smart.Default.Format("{0:list:{Name}|, |, and }", new object[] { data }); 
	Assert.AreEqual("Person A, Person B, and Person C", result);
	result = Smart.Default.Format("{0:list:{Name}|, |, and }", model.Persons);
	Assert.AreEqual("Person A, and Person C", result);
	result = Smart.Default.Format("{0:list:{Name}|, |, and }", data.Where(p => p.Gender == "F"));  
	Assert.AreEqual("Person B", result);
	result = Smart.Default.Format("{0:{Persons:{Name}|, }}", model);
	Assert.AreEqual("Person A, Person C", result);
}
```
Keep in mind: For now this is only working on the local machine, but not on dotnetfiddle.net

**Comment by mcanti** [comment]
Thanks for the clarifications!
